//
// Created by Ruto on 2/11/2017.
//

#ifndef NULLHTTPSERVER_NULLDEF_H
#define NULLHTTPSERVER_NULLDEF_H

#define READ_BUFFER_SIZE 512
#define WRITE_BUFFER_SIZE 512
#define PARSE_BUFFER_SIZE 512

#endif //NULLHTTPSERVER_NULLDEF_H
